Financial-Times/n-service-worker

main.js
package.json
src/__sw.js
src/lib/spoor.js
src/utils/db.js
webpack.config.js

Uses [indexeddb-promise](https://github.com/jakearchibald/indexeddb-promised), and give the periodic sync api a go (though don't think anything supports it)
Depends on https://github.com/Financial-Times/n-webpack/pull/15

Store failed spoor requests in IndexedDB

---

main.js

In an ideal world there'd be an API to handle any failure to register/update, but there isn't... so playing extra safe for now until we figure out the shielding issue in fastly (probably after the www move) @matthew-andrews

unregister service worker if cookie is too large

---

src/__sw.js
src/offline/content.js

Assumes the response from `https://session-next.ft.com/uuid` stored in cache is the current user's

Cache content, namespaced by uuid

---

src/push/myft.js
src/utils/flagged-toolbox.js
src/utils/flags.js

because service workers shut themselves down, losing global scope, and the spec is probably going to [change to allow browsers to spin up multiple sw instances](https://github.com/slightlyoff/ServiceWorker/issues/756), getting this out to make sure flags behave
@ironsidevsquincy

more persistent flag storage

---

src/offline/404-test.js
src/utils/offline-content.js

So that we can make further access decisions in the offline app.
Outgoing precache requests will also have a 'x-requested-with'
header.

new header on outgoing requests for precaching

---

config/precache.js
src/offline/404-test.js

Currently we always go to the network for fetch requests regardless of network state. This is safe as it means we'll always attempt to get the full version of article and not the offline version. However it has the penalty that we delay rendering the offline pages when genuinely offline as we have to wait for the network stack to fail first.
Therefore, this simply refactors the request routing strategy to use a `networkThenCache` strategy if `navigator.onLine` otherwise always use a `cacheThenNetwork` strategy.

Request strategy

---

src/caches/fonts.js

This fixes the disappearing fonts problem :wink: 
Turns out the fonts would be evicted from the offline cache as we weren't explicitly declaring a cache time.

Add an inifnite cache time to the font precache resources

---

config/precache.js

Caches `arrow-down` and `cross` icons
Before:
After:

add 'arrow-down' and 'cross' icons to precache

---

Makefile

Previously this would only match until the first .

Matches against -vx.x.x

---

appcache/iframe.html

Unfortunately we [can’t just add `aria-hidden` and omit a title](https://github.com/squizlabs/HTML_CodeSniffer/blob/master/Standards/WCAG2AAA/Sniffs/Principle2/Guideline2_4/2_4_1.js#L49)
@lc512k

Pass pa11y tests

---

appcache/generate.js

the old code was generating this:
```
CACHE:
https://www.ft.com/__origami/service/build/v2/files/o-fonts-assets@1.3.2/MetricWeb-Regular.woff?,/__origami/service/build/v2/files/o-fonts-assets@1.3.2/MetricWeb-Semibold.woff?,/__origami/service/build/v2/files/o-fonts-assets@1.3.2/FinancierDisplayWeb-Regular.woff?
https://www.ft.com/__origami/service/image/v2/images/raw/ftlogo:brand-ft-masthead?source=o-header&tint=%2333302E,%2333302E&format=svg,/__origami/service/image/v2/images/raw/fticon-v1:hamburger?source=o-icons&tint=%2333302E,%2333302E&format=svg,/__origami/service/image/v2/images/raw/fticon-v1:search?source=o-icons&tint=%2333302E,%2333302E&format=svg,/__origami/service/image/v2/images/raw/ftlogo:brand-myft?source=o-header&tint=%2333302E,%2333302E&format=svg
```
when really we want:
``` …
```

fix appache manifest cache section

---

package.json
src/__sw.js
src/utils/cache.js
test/__sw.spec.js

v2 of #142 
Moves cache clearing from `install` to `activate` so that it works as expected.

Improve the cleanup of old caches

---

src/caches/ads.js
test/unit/caches/ads.spec.js

The sw ads test didn't result in an uplift, which was weird. So a few thinsg in this (and the previous) PR
- Improve how flags and caches work, meaning there's less overhead in deciding whether to hit the network
- Stop precaching ads calls for section pages - most users don't visit these pages, so we're clogging up the bandwidth for most people for no gain
- stop being selective about which streams to cache using a huge regex - huge regexes can be very slow
Left some stuff commented out as we _may_ want to try some of it again later

less aggressive upfront ads caching

---

main.js

Should silence errors like this: https://sentry.io/nextftcom/ft-next-product-selector/issues/593825359

Squash useless 'UnknownError' from being thrown.

---

main.js

🐿 v2.5.16
Hangover from this PR: https://github.com/Financial-Times/n-service-worker/pull/138.
Should stop a lot of the "Service Worker unavailable" errors being triggered and sent to sentry

Delete temp flag passing to SW via message

---

karma.conf.js
package-lock.json

Pins the version of firefox that we run our Browserstack tests against to 64.0 as a temporary fix to unblock the repo while Browsersatck develop a more permanent one.
Details of the bug: [trello.com/c/pbQlK40K/654-firefox-latest-tests-broken-for-n-ui-and-n-myft-ui](https://trello.com/c/pbQlK40K/654-firefox-latest-tests-broken-for-n-ui-and-n-myft-ui)
🐿 v2.12.0

pins the version of firefox running our browserstack tests

---

main.js
test/integration/cache.spec.js

Fixes some of  the `cache cache invalidation` tests. The sw database is accessed async, so testing the expiry of an entry cannot be done accurately. The test was testing the expiry value  +/- 500ms to allow for discrepancies in async code execution time. On circle, this was just over the 500ms mark so I've increased this to +/- 1000ms to make sure this doesn't break again, but still accurate enough.

Fix max age test 🐿 v2.12.5

---

demos/app.js
package-lock.json
package.json

Replaced n-internal-tools for n-express
The file `fixtures.json` is no longer in the repository, so I've updated the demo so you just need to visit: `http://localhost:5005/demo.html`

replaced n-internal-tools for n-express

---

.circleci/config.yml

remove npm-install-peer-deps CI step since it's redundant after the migration to npm7

fix npm7 migration

---

README.md

As of today, there is no plan to remove the usage of this component from ft.com because it powers valuable features like `Desktop Instant alert in myFT`

Correct misleading information

---

.circleci/config.yml

This is to prevent issues with circleCI script and the way it resolves npm version. Context [here](https://financialtimes.slack.com/archives/C3TJ6KXEU/p1652356882216429)

Set NPM with exact version

---

package-lock.json
package.json

This shouldn't be necessary because when n-service-worker is installed by consuming apps it doesn't matter what version of npm is used. Besides, we'll be removing this when this repo upgrades to node 18.

Remove npm check
