Financial-Times/n-service-worker

__sw.js

@phamann @wheresrhys 
avoid troublesome redirect from the build service (v1 and unversioned endpoints have been removed).

use v2 of the Origami Build Service

---

main.js
src/__sw.js

pass flags in to sw to turn features on and off

---

main.js
src/lib/content.js
src/lib/flags.js

Also, before sending message wait for SW to be active (fixes bug where first time install was failing when immediately trying to send message)
cc @wheresrhys

Ability to send message to cache specific content

---

src/__sw.js
src/lib/built-assets.js
src/lib/content.js
src/lib/fonts.js
src/lib/image.js
src/utils/cache.js
src/utils/precache.js

Also
* roll our own `precache`, as sw toolbox's doesn't allow setting the cache name
* roll our own `cache`, as sw toolbox's doesn't allow setting the max age

Retrieve content from the cache

---

Makefile
src/lib/content.js

i.e. _don't_ minify in dev, _do_ minify in prod
Also, bonus, send credentials when fetching content

Correct webpack build options

---

src/lib/content.js

Rather icky, as making the request twice just so we can use the toolbox's cache expiration functionality
Need to pull that out into its own helper

Fix non-caching barriered content

---

main.js
src/__sw.js

See if `o-tracking` can handle this

Turning off spoor offline queuing

---

src/__sw.js
src/lib/myft.js
src/lib/session.js

caching session service responses

---

Makefile

so that doesn't have to go to s3 every time to check for updates @ironsidevsquincy

add surrogate cache headers

---

src/__sw.js

Cache 200s only

---

src/__sw.js
src/caches/ads.js
src/caches/built-assets.js
src/caches/comments.js
src/caches/fonts.js
src/caches/image.js
src/caches/myft.js
src/caches/n-ui.js
src/caches/polyfill.js
src/caches/session.js
src/offline/content.js
src/utils/cache.js
src/utils/db.js
src/utils/flags.js
src/utils/handlers.js
src/utils/personal.js
src/utils/precache.js

Which allows expiration fucntionality

Add cache util

---

src/caches/built-assets.js
src/caches/fonts.js
src/caches/n-ui.js
test/caches/built-assets.spec.js
test/caches/fonts.spec.js
test/caches/image.spec.js
test/caches/n-ui.spec.js

@tavvy @JakeChampion @rowanmanning

removed geebee urls (apart from polyfill)

---

Makefile
appcache/generate.js
appcache/iframe.html
appcache/loader.html
config/precache.js
package.json
src/caches/fonts.js
src/caches/image.js
webpack.config.js

generates appcache manifest

---

config/precache.js

cache refresh icon

---

config/idb-client-map.js
src/messages/controllers/cache-meta-lookup.js
src/messages/controllers/client-id-lookup.js
src/messages/controllers/index.js
src/messages/index.js
src/messages/routing.js
src/offline/404-test.js
src/utils/cache.js
src/utils/db.js
src/utils/precache.js

Client side looks like:
```
sendMessage('getCacheMeta', {
url: 'https://local.ft.com:5050/content/4cb3074e-c11a-11e6-81c2-f57d90f6741a'
})
.then(res => HANDLE RESPONSE)
.catch(err => HANDLE ERROR)
sendMessage('getCacheMeta')
.then(res => HANDLE RESPONSE)
.catch(err => HANDLE ERROR)
```

Cache meta lookup

---

appcache/generate.js
config/precache.js
src/caches/fonts.js
src/caches/image.js

@tavvy 
While the overlap isn't so serious at the moment, I still think it's good to establish in the code that precaching and in sw are different decisions

appcache != sw precache

---

main.js
src/messages/index.js
src/offline/404-test.js

So that we can show toasts to the client

Send both window and client post messages on cache events

---

src/__sw.js
src/push/myft.js
src/utils/eager-fetch.js
src/utils/track.js

For now this is pretty much just a move of files that were previosuly
used for push notifications. There has been some very small changes.
One improvement I can see straight away would be to refactor the
`track.js` to work with the `src/offline/spoor.js` which also exists. I
wanted to leave this for now though whilst we get everything set up
again.

Enable push notifications to be processed on the client

---

.pa11yci.js
Makefile
demo/app.js
demo/demo.html
demo/fixtures.json
package.json

And pa11y runs over it
cc: @keirog

Add demo page

---

main.js

Worth noting: the logic for this is the antithesis to what's in https://github.com/Financial-Times/n-ui/pull/1037
🐿2.5.10

Only disable install prompt when flags aren't set

---

src/caches/polyfill.js
test/caches/polyfill.spec.js

fix polyfill service url

---

Makefile
webpack.config.js

fix source maps in prod

---

config/precache.js
test/caches/fonts.spec.js

... on first load (by o-fonts CSS in our critical CSS, and again by Service Worker)

removing question marks in a bid to prevent downloading each font twice

---

.gitignore
karma.conf.js
secret-squirrel.js
src/__sw.js
src/caches/ads.js
test/caches/ads.spec.js

Caching ads calls

---

karma.conf.js
src/utils/cache.js
src/utils/handlers.js
test/caches/polyfill.spec.js

fixes https://github.com/Financial-Times/n-service-worker/issues/131

Fix insane number of responses generated by expireAll

---

Makefile
circle.yml
karma.conf.js
package.json
src/caches/ads.js
src/caches/fonts.js
src/caches/image.js
src/utils/handlers.js
src/utils/precache.js
test/caches/ads.spec.js
test/main.spec.js
test/test-bundles.js
webpack.config.js

* use webpack 3 instead
* dependency hygiene
* address sinon & chai breaking changes
Changes to `Makefile` can be reverted safely when https://github.com/Financial-Times/n-gage/pull/83 is merged (`n-gage` minor release).
🐿 v2.5.16

decouple n-webpack

---

config/precache.js
src/__sw.js
src/caches/ads.js
src/caches/built-assets.js
src/caches/comments.js
src/caches/fonts.js
src/caches/image.js
src/caches/myft.js
src/caches/polyfill.js
src/caches/session.js
test/caches/ads.spec.js
test/caches/built-assets.spec.js
test/caches/fonts.spec.js
test/caches/image.spec.js
test/caches/polyfill.spec.js

Not sure if we should bother with the addition to the `install` event.

Version cache names

---

main.js

This error was still making it through somehow. Hopefully this silences it.
🐿 v2.8.0

Catch indexedDB error properly

---

src/push/myft.js

This is so we can track the effectiveness of myFT instant alert push notifications.
https://trello.com/c/lV8PhYrz/3490-track-push-notifications

Include segmentId if it's available

---

package-lock.json
package.json

migration `master` to `main`: upgrade to n-gage 8

upgrade to n-gage 8

---

.circleci/config.yml
package-lock.json
package.json

Npm 7 migration

---

package.json

Update check-engine script according to the official NPM7 migration script https://gist.github.com/aasanchez/26ef84d0b602dd3eae0b21e1dac1a30a#file-npm7-sh-L126

fix check-engine script

---

.circleci/config.yml
package-lock.json
package.json

Rollback migration to node 14 done in [this PR](https://github.com/Financial-Times/n-service-worker/pull/180)
Added Volta in order to pin Node 12 and NPM 7

rollback to node12

---

.circleci/config.yml
package-lock.json
package.json

Upgrade from Node 12 to Node 16

CON-1695 upgrade node

---

.circleci/config.yml

fix upgrade to node 16 by using a newer version of the docker image

fix circleci image

---

README.md

This PR is a part of [decommission myFT desktop push notifications and n-service-worker](https://financialtimes.atlassian.net/browse/CON-3128)

Update README about the decommission
